FROM postgres:14.7
ENV POSTGRES_DB=ecomm
ENV POSTGRES_PASSWORD=avizva9372
COPY ./ecomm.sql /docker-entrypoint-initdb.d/ecomm.sql
COPY ./install-pgcrypto.sh /docker-entrypoint-initdb.d/install-pgcrypto.sh
RUN chown -R postgres:postgres /docker-entrypoint-initdb.d/