FROM postgres:14.7

# Environment variables for PostgreSQL
ENV POSTGRES_DB=azerty
ENV POSTGRES_PASSWORD=azerty

# Set the working directory
WORKDIR /docker-entrypoint-initdb.d

# Copy initialization scripts
COPY ./ecomm.sql /docker-entrypoint-initdb.d/ecomm.sql
COPY ./install-pgcrypto.sh /docker-entrypoint-initdb.d/install-pgcrypto.sh

# Ensure scripts are executable
RUN chmod +x /docker-entrypoint-initdb.d/install-pgcrypto.sh

# Set ownership to the postgres user
RUN chown -R postgres:postgres /docker-entrypoint-initdb.d/

# This runs the parent entrypoint script (from postgres image)
CMD ["docker-entrypoint.sh", "postgres"]