server:
  port: 8083
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: info

host:
  user-service:
    url: ${USER_SERVICE_URL}
    port: ${USER_SERVICE_PORT}
  cart-service:
    url: ${CART_SERVICE_URL}
    port: ${CART_SERVICE_PORT}

stripe:
  api-key: ${STRIPE_API_KEY}

springdoc:
  swagger-ui:
    path: /swagger-ui
    enabled: true
  api-docs:
    enabled: true
    path: /api-docs
